    // AT45DBxx DataFlash memories

    (b0:$0C; b1:$FF; b2:$FF;
    name:'AT45DB011B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:135168; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$0C; b1:$1F; b2:$22;
    name:'AT45DB011D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:135168; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$0D; b1:$1F; b2:$22;
    name:'AT45DB011D /256';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:135168; esize:0; usigsize:0; fpage:8; fpagesize:256; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$14; b1:$FF; b2:$FF;
    name:'AT45DB021B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:270336; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$14; b1:$1F; b2:$23;
    name:'AT45DB021D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:270336; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$15; b1:$1F; b2:$23;
    name:'AT45DB021D /256';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:270336; esize:0; usigsize:0; fpage:8; fpagesize:256; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$1C; b1:$FF; b2:$FF;
    name:'AT45DB041B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:540672; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$1C; b1:$1F; b2:$24;
    name:'AT45DB041D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:540672; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$1D; b1:$1F; b2:$24;
    name:'AT45DB041D /256';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:540672; esize:0; usigsize:0; fpage:8; fpagesize:256; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$24; b1:$FF; b2:$FF;
    name:'AT45DB081B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:1081344; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$24; b1:$1F; b2:$25;
    name:'AT45DB081D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:1081344; esize:0; usigsize:0; fpage:9; fpagesize:264; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$25; b1:$1F; b2:$25;
    name:'AT45DB081D /256';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:1081344; esize:0; usigsize:0; fpage:8; fpagesize:256; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$2C; b1:$FF; b2:$FF;
    name:'AT45DB161B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:2162688; esize:0; usigsize:0; fpage:10; fpagesize:528; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$2C; b1:$1F; b2:$26;
    name:'AT45DB161D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:2162688; esize:0; usigsize:0; fpage:10; fpagesize:528; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$2D; b1:$1F; b2:$26;
    name:'AT45DB161D /512';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:2162688; esize:0; usigsize:0; fpage:9; fpagesize:512; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$34; b1:$FF; b2:$FF;
    name:'AT45DB321B';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:4325376; esize:0; usigsize:0; fpage:10; fpagesize:528; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$34; b1:$1F; b2:$27;
    name:'AT45DB321C/D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:4325376; esize:0; usigsize:0; fpage:10; fpagesize:528; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$35; b1:$1F; b2:$27;
    name:'AT45DB321D /512';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:4325376; esize:0; usigsize:0; fpage:9; fpagesize:512; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$3C; b1:$1F; b2:$28;
    name:'AT45DB642D';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:8650752; esize:0; usigsize:0; fpage:11; fpagesize:1056; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$3D; b1:$1F; b2:$28;
    name:'AT45DB642D /1024';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:8650752; esize:0; usigsize:0; fpage:10; fpagesize:1024; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','','')),

    (b0:$10; b1:$1F; b2:$29;
    name:'AT45CS1282';
    proctype:PROC_TYPE_DATAFLASH;
    fsize:17301504; esize:0; usigsize:0; fpage:11; fpagesize:1056; epage:0; epagesize:0;
    osccal:0;
    algo:ALGO_DATAFLASH;
    algo_erase:ALGO_ERASE_STD;
    algo_lb:ALGO_LB_NONE;
    algo_busy:ALGO_BUSY_DATAFLASH;
    prog_time:20;
    lockbits:('','','','','','','','');
    fusebitslo:('','','','','','','','');
    fusebitshi:('','','','','','','','');
    fusebitsext:('','','','','','','',''))
    
